package main_test

import (
	"strings"
	"testing"
)

// TestInspectNamesThePackageItWasAskedFor checks that an external test package
// is not reported in place of its subject. It declares into its own scope with
// its own namespaces, so answering with it would hand back a different package
// under the asked-for name.
func TestInspectNamesThePackageItWasAskedFor(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, "go.mod", testModule)
	writeTree(t, dir, "q/q.go", "package q\n\nfunc Run() int { return 1 }\n")
	// Two external test files, so the external package holds more files than
	// its subject and would win any widest-variant contest.
	writeTree(t, dir, "q/a_test.go", "package q_test\n\nimport \"testing\"\n\nfunc TestA(t *testing.T) {}\n")
	writeTree(t, dir, "q/b_test.go", "package q_test\n\nimport \"testing\"\n\nfunc TestB(t *testing.T) {}\n")

	out, code := runIn(t, bin, dir, "inspect", "./q")
	if code != 0 {
		t.Fatalf("inspect exited %d\n%s", code, out)
	}
	if !strings.Contains(out, "# example.com/declscopetest/q\n") {
		t.Errorf("inspect reported another package:\n%s", out)
	}
}

// TestInspectRefusesMoreThanOnePackage pins the refusal a namespace's meaning
// depends on: two packages can spell one the same way and mean nothing in
// common, so their counts cannot be shown together or averaged.
func TestInspectRefusesMoreThanOnePackage(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, "go.mod", testModule)
	writeTree(t, dir, "a/a.go", "package a\n\nfunc Run() int { return 1 }\n")
	writeTree(t, dir, "b/b.go", "package b\n\nfunc Run() int { return 1 }\n")

	out, code := runIn(t, bin, dir, "inspect", "./...")
	if code == 0 {
		t.Fatalf("inspect measured two packages at once\n%s", out)
	}
	for _, want := range []string{"matches 2 packages", "example.com/declscopetest/a", "example.com/declscopetest/b"} {
		if !strings.Contains(out, want) {
			t.Errorf("the refusal does not name %q:\n%s", want, out)
		}
	}
}

// TestInspectDoesNotMistakeARealTestSuffixForAnExternalTest checks that an
// ordinary package named q_test is not discarded merely because q is present.
func TestInspectDoesNotMistakeARealTestSuffixForAnExternalTest(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, "go.mod", testModule)
	writeTree(t, dir, "q/q.go", "package q\n\nfunc Run() int { return 1 }\n")
	writeTree(t, dir, "q_test/q.go", "package q_test\n\nfunc Run() int { return 1 }\n")

	out, code := runIn(t, bin, dir, "inspect", "./...")
	if code == 0 {
		t.Fatalf("inspect discarded the real q_test package\n%s", out)
	}
	for _, want := range []string{"matches 2 packages", "example.com/declscopetest/q", "example.com/declscopetest/q_test"} {
		if !strings.Contains(out, want) {
			t.Errorf("the refusal does not name %q:\n%s", want, out)
		}
	}
}

// TestInspectIgnoresErrorsInTheSkippedExternalTestPackage checks that inspect
// can still report q when q_test, which it deliberately does not report, fails
// to type-check.
func TestInspectIgnoresErrorsInTheSkippedExternalTestPackage(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, "go.mod", testModule)
	writeTree(t, dir, "q/q.go", "package q\n\nfunc Run() int { return 1 }\n")
	writeTree(t, dir, "q/q_test.go", "package q_test\n\nfunc broken() { undefinedThing() }\n")

	out, code := runIn(t, bin, dir, "inspect", "./q")
	if code != 0 {
		t.Fatalf("inspect was blocked by the external package it skips: exit %d\n%s", code, out)
	}
	if !strings.Contains(out, "# example.com/declscopetest/q\n") {
		t.Errorf("inspect did not report the requested package:\n%s", out)
	}
}

// TestInspectWithoutAPackagePrintsUsage checks the one argument inspect
// insists on. survey and baseline default to ./..., and inspect cannot: it
// answers for one package, and defaulting would pick one silently.
func TestInspectWithoutAPackagePrintsUsage(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, "go.mod", testModule)

	out, code := runIn(t, bin, dir, "inspect")
	if code != 2 {
		t.Fatalf("inspect with no package exited %d, want 2\n%s", code, out)
	}
	if !strings.Contains(out, "inspect") || !strings.Contains(out, "-format") {
		t.Errorf("the usage does not describe the subcommand:\n%s", out)
	}
}

// TestInspectSaysNothingWasChecked covers the report for a package every file
// of which was excluded — here because all of it is generated. Its tables are
// empty, and empty tables read as a clean package, so the report opens by
// saying that nothing was read rather than letting the zeros speak.
func TestInspectSaysNothingWasChecked(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, "go.mod", testModule)
	writeTree(t, dir, "p/zz_gen.go",
		"// Code generated by a tool. DO NOT EDIT.\n\npackage p\n\nfunc genHelper() int { return 1 }\n\nvar _ = genHelper\n")

	out, code := runIn(t, bin, dir, "inspect", "./p")
	if code != 0 {
		t.Fatalf("inspect exited %d\n%s", code, out)
	}
	if !strings.Contains(out, "No file of this package was read") {
		t.Errorf("a package with nothing read should say so:\n%s", out)
	}
}

// TestInspectRefusesWhatItCannotMeasure covers the three answers that are not
// a report. Each one is a refusal rather than an empty table, because a
// package that did not load, did not compile, or was never named yields the
// same zeros as a package with nothing wrong.
func TestInspectRefusesWhatItCannotMeasure(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, "go.mod", testModule)
	writeTree(t, dir, "p/p.go", "package p\n\nfunc Run() int { return 1 }\n")
	writeTree(t, dir, "broken/broken.go", "package broken\n\nfunc Run() int { return nope }\n")

	tests := []struct {
		name string
		args []string
		want string
	}{
		{"an unknown format", []string{"-format=toml", "./p"}, "toml"},
		{"a pattern nothing matches", []string{"./nope"}, "./nope"},
		{"a package that does not compile", []string{"./broken"}, "do not type-check"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			out, code := runIn(t, bin, dir, append([]string{"inspect"}, tt.args...)...)
			if code == 0 {
				t.Fatalf("inspect answered anyway:\n%s", out)
			}
			if !strings.Contains(out, tt.want) {
				t.Errorf("the refusal does not name %q:\n%s", tt.want, out)
			}
		})
	}
}

// TestInspectTakesTheConfigItWasGiven checks that -config replaces the chain
// the report names, the way it does for survey: the caller named the rules, so
// the file beside the package is not what ran.
func TestInspectTakesTheConfigItWasGiven(t *testing.T) {
	dir := t.TempDir()
	writeTree(t, dir, "go.mod", testModule)
	writeTree(t, dir, "chosen.yaml", "rules:\n  naming:\n    qualify: always\n")
	writeTree(t, dir, "p/.declscope.yaml", "rules:\n  naming:\n    qualify: never\n")
	writeTree(t, dir, "p/user.go", "package p\n\nfunc helper() int { return 1 }\n\nvar _ = helper\n")

	out, code := runIn(t, bin, dir, "inspect", "-config=chosen.yaml", "./p")
	if code != 0 {
		t.Fatalf("inspect exited %d\n%s", code, out)
	}
	if !strings.Contains(out, "chosen.yaml") {
		t.Errorf("the report does not name the config it was given:\n%s", out)
	}
	if strings.Contains(out, ".declscope.yaml") {
		t.Errorf("the report names a config that did not run:\n%s", out)
	}
}
