package main_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// inspectorModule exercises every walk the analyzer makes through the
// inspector. p reaches helper and userPoint's fields by ident and by an unkeyed
// literal, and gen.go names helper from a file the pass does not collect. q
// pairs model's fields by a conversion, which keeps their directives, and
// converts ledger only to itself, which does not.
var inspectorModule = map[string]string{
	"go.mod":          testModule,
	".declscope.yaml": "rules:\n  naming:\n    qualify: ondemand\n",
	"p/user.go":       "package p\n\nfunc helper() int { return 1 }\n\ntype userPoint struct{ x, y int }\n\ntype userA struct {\n\t//declscope:package\n\tn int\n\t//declscope:package\n\tm int\n}\n",
	"p/order.go":      "package p\n\ntype orderB struct {\n\tn int\n\tm int\n}\n\nfunc orderConv(a userA) orderB { return orderB(a) }\n\nfunc orderRun() int {\n\tp := userPoint{1, 2}\n\treturn helper() + p.x\n}\n\nvar _ = orderConv\nvar _ = orderRun\n",
	"p/gen.go":        "// Code generated by hand. DO NOT EDIT.\n\npackage p\n\nfunc genUse() int { return helper() }\n\nvar _ = genUse\n",
	"q/model.go":      "package q\n\ntype model struct {\n\tID int\n\t//declscope:package\n\trev int\n\t//declscope:package\n\tseq int\n}\n\n//declscope:package\nfunc modelNew() model { return model{ID: 1, rev: 2, seq: 3} }\n\ntype ledger struct {\n\t//declscope:package\n\tn int\n}\n\n//declscope:package\nfunc ledgerNew() ledger { return ledger{n: 1} }\n",
	"q/snapshot.go":   "package q\n\ntype snapshot struct {\n\tID  int\n\trev int\n\tseq int\n}\n\nfunc snapshotOf() snapshot { return snapshot(modelNew()) }\n\nvar _ = snapshotOf\n\nfunc snapshotLedger() ledger { return ledger(ledgerNew()) }\n\nvar _ = snapshotLedger\n",
}

// TestSubcommandsAnalyzeThroughTheInspector checks that the subcommands,
// which build their own pass, hand the analyzer the inspector it requires and
// read the same output from it. The goldens were written by the binary from
// before the analyzer required the inspector, so any change in what a walk
// visits shows up as a diff.
func TestSubcommandsAnalyzeThroughTheInspector(t *testing.T) {
	root := t.TempDir()
	for name, body := range inspectorModule {
		writeTree(t, root, name, body)
	}
	for _, tc := range []struct {
		golden string
		args   []string
	}{
		{"analyzer.txt", []string{"./..."}},
		// The fixes are where a name used from gen.go shows: helper is
		// offered no rename.
		{"analyzer-p.json", []string{"-json", "./p"}},
		{"survey.json", []string{"survey", "-format=json", "./..."}},
		{"inspect-p.json", []string{"inspect", "-format=json", "./p"}},
		{"inspect-q.json", []string{"inspect", "-format=json", "./q"}},
		{"baseline.txt", []string{"baseline", "-o", "baseline.yaml", "./..."}},
	} {
		out, _ := runIn(t, bin, root, tc.args...)
		inspectorCompare(t, root, tc.golden, out)
	}
	written, err := os.ReadFile(filepath.Join(root, "baseline.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	inspectorCompare(t, root, "baseline.yaml", string(written))
}

func inspectorCompare(t *testing.T, root, golden, got string) {
	t.Helper()
	want, err := os.ReadFile(filepath.Join("testdata", "inspector", golden))
	if err != nil {
		t.Fatal(err)
	}
	if got = strings.ReplaceAll(got, root, "$ROOT"); got != string(want) {
		t.Errorf("%s changed:\n--- got ---\n%s\n--- want ---\n%s", golden, got, want)
	}
}
